// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^4.4.3";
import { events } from "npm:@/data/events";
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List Ronda Priv\xE9 showcase events (festivals, concerts, nightclubs, conferences). Optionally filter by status or category.",
  inputSchema: {
    status: z.enum(["active", "upcoming"]).optional().describe("Filter by event status."),
    category: z.enum(["festival", "concert", "nightclub", "conference", "bar"]).optional().describe("Filter by event category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, category }) => {
    const rows = events.filter((e) => status ? e.status === status : true).filter((e) => category ? e.category === category : true).map((e) => ({
      id: e.id,
      name: e.name,
      venue: e.venue,
      city: e.city,
      status: e.status,
      category: e.category,
      features: e.features,
      rating: e.rating,
      attendees: e.attendees
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { events: rows }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { events as events2 } from "npm:@/data/events";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event details",
  description: "Get full details for one Ronda Priv\xE9 event by id, including vendors and menus.",
  inputSchema: {
    id: z2.string().min(1).describe("The event id (e.g. 'estereo-picnic-2026').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const event = events2.find((e) => e.id === id);
    if (!event) {
      return {
        content: [{ type: "text", text: `No event found with id '${id}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(event, null, 2) }],
      structuredContent: { event }
    };
  }
});

// src/lib/mcp/tools/list-faq.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z3 } from "npm:zod@^4.4.3";
import { faqItems } from "npm:@/data/faq";
import es from "npm:@/i18n/locales/es.json";
var faqDict = es.faq ?? {};
var asString = (v) => typeof v === "string" ? v : "";
var list_faq_default = defineTool3({
  name: "list_faq",
  title: "List FAQ",
  description: "List Ronda Priv\xE9 frequently asked questions with answers (Spanish). Optionally filter by category.",
  inputSchema: {
    category: z3.enum(["general", "attendees", "organizers", "technical"]).optional().describe("Filter by FAQ category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const rows = faqItems.filter((f) => category ? f.category === category : true).map((f) => ({
      id: f.id,
      category: f.category,
      question: asString(faqDict[f.questionKey.replace(/^faq\./, "")]),
      answer: asString(faqDict[f.answerKey.replace(/^faq\./, "")])
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { faq: rows }
    };
  }
});

// src/lib/mcp/tools/list-glossary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z4 } from "npm:zod@^4.4.3";
import { GLOSSARY_TERMS } from "npm:@/data/glossary";
import es2 from "npm:@/i18n/locales/es.json";
var terms = es2.glossary?.terms ?? {};
var list_glossary_default = defineTool4({
  name: "list_glossary",
  title: "List glossary",
  description: "List Ronda Priv\xE9 industry glossary terms with definitions (Spanish). Optionally filter by category or search text.",
  inputSchema: {
    category: z4.enum(["sales", "venue", "tech", "spaces", "metrics"]).optional().describe("Filter by glossary category."),
    search: z4.string().optional().describe("Case-insensitive substring match on term or definition.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, search }) => {
    const q = search?.toLowerCase();
    const rows = GLOSSARY_TERMS.filter((g) => category ? g.category === category : true).map((g) => ({
      id: g.id,
      category: g.category,
      term: terms[g.id]?.term ?? g.id,
      definition: terms[g.id]?.definition ?? ""
    })).filter((r) => q ? r.term.toLowerCase().includes(q) || r.definition.toLowerCase().includes(q) : true);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { glossary: rows }
    };
  }
});

// src/lib/mcp/tools/list-insights.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z5 } from "npm:zod@^4.4.3";
import { insights } from "npm:@/data/insights";
import es3 from "npm:@/i18n/locales/es.json";
var dict = es3.insights ?? {};
var list_insights_default = defineTool5({
  name: "list_insights",
  title: "List insights",
  description: "List Ronda Priv\xE9 insight articles (blog posts) with title and excerpt (Spanish). Optionally filter by category.",
  inputSchema: {
    category: z5.enum(["trends", "cases", "product", "industry"]).optional().describe("Filter by insight category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const rows = insights.filter((p) => category ? p.category === category : true).map((p) => {
      const key = p.titleKey.replace(/^insights\./, "").replace(/\.title$/, "");
      const entry = dict[key] ?? {};
      return {
        id: p.id,
        slug: p.slug,
        category: p.category,
        date: p.date,
        readTime: p.readTime,
        title: entry.title ?? "",
        excerpt: entry.excerpt ?? "",
        url: `https://rondaprive.com/es/insights/${p.slug}`
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { insights: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ronda-prive-mcp",
  title: "Ronda Priv\xE9",
  version: "0.1.0",
  instructions: "Public tools for Ronda Priv\xE9 (rondaprive.com), an event-monetization platform for arenas, festivals and venues. Use these tools to browse showcase events, look up FAQ answers, glossary terms and insight articles.",
  tools: [list_events_default, get_event_default, list_faq_default, list_glossary_default, list_insights_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
