// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list-events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^4.4.3";

// src/data/events.ts
var rawEvents = [
  {
    id: "estereo-picnic-2026",
    name: "Festival Est\xE9reo Picnic 2026",
    date: "",
    venue: "Parque Sim\xF3n Bol\xEDvar",
    city: "Bogot\xE1",
    image: "https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800&q=80",
    features: ["pickup", "seat", "preorder"],
    status: "active",
    description: "",
    category: "festival",
    rating: 4.9,
    attendees: "85,000",
    vendors: [
      {
        id: "bar-central",
        name: "Bar Central",
        type: "bar",
        menu: [
          { id: "b1", name: "Gin & Tonic Premium", price: 8500, category: "Cocktails" },
          { id: "b2", name: "Aperol Spritz", price: 7500, category: "Cocktails" },
          { id: "b3", name: "Cerveza Artesanal", price: 4500, category: "Cervezas" }
        ]
      }
    ]
  },
  {
    id: "copa-libertadores-2026",
    name: "Final Copa Libertadores",
    date: "",
    venue: "Estadio Monumental",
    city: "Buenos Aires",
    image: "https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&q=80",
    features: ["pickup", "seat"],
    status: "active",
    description: "",
    category: "concert",
    rating: 4.8,
    attendees: "72,000",
    vendors: [
      {
        id: "cantina",
        name: "Cantina Norte",
        type: "food",
        menu: [
          { id: "cn1", name: "Choripan", price: 3500, category: "Clasicos" },
          { id: "cn2", name: "Cerveza Quilmes", price: 3e3, category: "Bebidas" }
        ]
      }
    ]
  },
  {
    id: "tomorrowland-winter-2026",
    name: "Tomorrowland Winter",
    date: "",
    venue: "Alpe d'Huez",
    city: "Alpe d'Huez",
    image: "https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800&q=80",
    features: ["pickup", "preorder"],
    status: "active",
    description: "",
    category: "festival",
    rating: 4.8,
    attendees: "30,000",
    vendors: [
      {
        id: "bar-tmrw",
        name: "Main Bar",
        type: "bar",
        menu: [
          { id: "t1", name: "Heineken", price: 6e3, category: "Cervezas" }
        ]
      }
    ]
  },
  {
    id: "club-prive-madrid",
    name: "Club Priv\xE9 Madrid",
    date: "",
    venue: "Club Priv\xE9",
    city: "Madrid",
    image: "https://images.unsplash.com/photo-1566737236500-c8ac43014a67?w=800&q=80",
    features: ["pickup", "seat"],
    status: "active",
    description: "",
    category: "nightclub",
    rating: 4.7,
    vendors: [
      {
        id: "vip-madrid",
        name: "VIP Lounge",
        type: "vip",
        menu: [
          { id: "vm1", name: "Champagne Moet", price: 45e3, category: "Premium" }
        ]
      }
    ]
  },
  {
    id: "tech-summit-2026",
    name: "Tech Summit 2026",
    date: "",
    venue: "Fira Barcelona",
    city: "Miami, USA",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    features: ["pickup", "preorder"],
    status: "upcoming",
    description: "",
    category: "conference",
    rating: 4.6,
    vendors: [
      {
        id: "catering-tech",
        name: "Catering",
        type: "food",
        menu: [
          { id: "ct1", name: "Box Lunch Premium", price: 15e3, category: "Lunch" }
        ]
      }
    ]
  },
  {
    id: "lollapalooza-chile-2026",
    name: "Lollapalooza Chile",
    date: "",
    venue: "Parque Cerrillos",
    city: "Santiago",
    image: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80",
    features: ["pickup", "preorder"],
    status: "upcoming",
    description: "",
    category: "festival",
    rating: 4.8,
    vendors: [
      {
        id: "bar-lolla",
        name: "Heineken Bar",
        type: "bar",
        menu: [
          { id: "l1", name: "Heineken Pint", price: 4e3, category: "Cervezas" }
        ]
      }
    ]
  }
];
var events = rawEvents;

// src/lib/mcp/tools/list-events.ts
var list_events_default = defineTool({
  name: "list_events",
  title: "List events",
  description: "List Ronda Priv\xE9 showcase events (festivals, concerts, nightclubs, conferences). Optionally filter by status or category.",
  inputSchema: {
    status: z.enum(["active", "upcoming"]).optional().describe("Filter by event status."),
    category: z.enum(["festival", "concert", "nightclub", "conference", "bar"]).optional().describe("Filter by event category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status, category }) => {
    const rows = events.filter((e) => status ? e.status === status : true).filter((e) => category ? e.category === category : true).map((e) => ({
      id: e.id,
      name: e.name,
      venue: e.venue,
      city: e.city,
      status: e.status,
      category: e.category,
      features: e.features,
      rating: e.rating,
      attendees: e.attendees
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { events: rows }
    };
  }
});

// src/lib/mcp/tools/get-event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z2 } from "npm:zod@^4.4.3";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Get event details",
  description: "Get full details for one Ronda Priv\xE9 event by id, including vendors and menus.",
  inputSchema: {
    id: z2.string().min(1).describe("The event id (e.g. 'estereo-picnic-2026').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const event = events.find((e) => e.id === id);
    if (!event) {
      return {
        content: [{ type: "text", text: `No event found with id '${id}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(event, null, 2) }],
      structuredContent: { event }
    };
  }
});

// src/lib/mcp/tools/list-faq.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z3 } from "npm:zod@^4.4.3";

// src/data/faq.ts
var faqItems = [
  { id: "faq-1", category: "general", questionKey: "faq.q1", answerKey: "faq.a1" },
  { id: "faq-2", category: "general", questionKey: "faq.q2", answerKey: "faq.a2" },
  { id: "faq-3", category: "general", questionKey: "faq.q3", answerKey: "faq.a3" },
  { id: "faq-4", category: "technical", questionKey: "faq.q4", answerKey: "faq.a4" },
  { id: "faq-5", category: "organizers", questionKey: "faq.q5", answerKey: "faq.a5" },
  { id: "faq-6", category: "organizers", questionKey: "faq.q6", answerKey: "faq.a6" },
  { id: "faq-7", category: "attendees", questionKey: "faq.q7", answerKey: "faq.a7" },
  { id: "faq-8", category: "organizers", questionKey: "faq.q8", answerKey: "faq.a8" },
  { id: "faq-9", category: "organizers", questionKey: "faq.q9", answerKey: "faq.a9" },
  { id: "faq-10", category: "technical", questionKey: "faq.q10", answerKey: "faq.a10" },
  { id: "faq-11", category: "technical", questionKey: "faq.q11", answerKey: "faq.a11" },
  { id: "faq-12", category: "attendees", questionKey: "faq.q12", answerKey: "faq.a12" },
  { id: "faq-13", category: "general", questionKey: "faq.q13", answerKey: "faq.a13" }
];

// src/i18n/locales/es.json
var es_default = {
  navbar: {
    menu: "Men\xFA",
    solutions: "Soluciones",
    industries: "Industrias",
    howItWorks: "C\xF3mo funciona",
    insights: "Insights",
    exploreEvents: "Explorar eventos",
    requestDemo: "Solicitar demo",
    product: "Producto",
    benefits: "Beneficios",
    dashboard: "Panel",
    contact: "Contacto"
  },
  hero: {
    badge: "Plataforma m\xF3vil para eventos y venues",
    headlineLine1: "Elimina la espera.",
    headlineLine2: "Maximiza las ventas.",
    ctaDemo: "Solicitar demo",
    mockup: {
      welcome: "Bienvenido a",
      festivalName: "Festival 2026",
      festivalDate: "26-30 Marzo",
      featurePreorder: "Compra anticipada",
      featureSeat: "Compra desde el asiento",
      featureExpress: "Express",
      orderNow: "Pedir ahora",
      orderTime: "Tiempo pedido",
      noQueues: "Sin filas",
      noQueuesSub: "En todo el recinto"
    }
  },
  problem: {
    label: "El problema",
    title: "Las filas",
    titleHighlight: "matan las ventas",
    items: [
      {
        title: "Ventas perdidas",
        description: "Los asistentes abandonan la fila antes de comprar. Cada minuto de espera es dinero que se pierde."
      },
      {
        title: "Experiencia arruinada",
        description: "Nadie quiere perderse el show por una bebida. La frustraci\xF3n reduce el consumo y la satisfacci\xF3n."
      },
      {
        title: "Staff saturado",
        description: "Cuellos de botella, estr\xE9s y errores en pedidos. La operaci\xF3n colapsa en momentos de alta demanda."
      },
      {
        title: "Cero visibilidad",
        description: "Sin datos en tiempo real, sin control de inventario, sin capacidad de reacci\xF3n ante picos de demanda."
      }
    ]
  },
  solutionsOverview: {
    label: "Soluciones",
    title: "Tres formas de",
    titleHighlight: "vender m\xE1s",
    subtitle: "Cada modalidad se adapta al tipo de evento, recinto y experiencia que necesitas ofrecer.",
    pickup: {
      title: "Compra y Retira",
      description: "El asistente compra desde su celular y retira en el punto de venta cuando su pedido est\xE1 listo. Sin filas, sin esperas.",
      cta: "Ver detalle"
    },
    seat: {
      title: "Compra desde el asiento",
      description: "Escanea el QR en tu asiento, mesa o sector. Compra y recibe tu pedido directamente en tu ubicaci\xF3n.",
      cta: "Ver detalle"
    },
    preorder: {
      title: "Compra anticipada",
      description: "Compra antes del evento, paga por adelantado y el d\xEDa del evento solo retira presentando tu QR.",
      cta: "Ver detalle"
    }
  },
  howItWorks: {
    label: "C\xF3mo funciona",
    title: "Simple para todos.",
    titleHighlight: "Potente para tu operaci\xF3n.",
    subtitle: "Desde el primer pedido hasta la entrega, cada paso est\xE1 dise\xF1ado para maximizar velocidad y control.",
    tabs: {
      attendee: "Para asistentes",
      kitchen: "Para barra y cocina",
      organizer: "Para organizadores"
    },
    attendee: {
      steps: [
        {
          title: "Accede a Ronda Priv\xE9",
          description: "Escanea el QR del evento o ingresa desde el link directo."
        },
        {
          title: "Explora la carta digital",
          description: "Ve los productos disponibles, precios y opciones de cada punto de venta."
        },
        {
          title: "Realiza tu compra",
          description: "Selecciona, paga desde tu celular y recibe un c\xF3digo QR de confirmaci\xF3n."
        },
        {
          title: "Retira o recibe",
          description: "Ac\xE9rcate al punto de retiro o recibe en tu asiento. Sin filas."
        }
      ]
    },
    kitchen: {
      steps: [
        {
          title: "Recibe el pedido",
          description: "El equipo operativo visualiza cada pedido con detalle de productos, cliente y ubicaci\xF3n."
        },
        {
          title: "Inicia preparaci\xF3n",
          description: "El personal marca el estado: recibido, en preparaci\xF3n, listo."
        },
        {
          title: "Escanea y entrega",
          description: "En Compra y Retira se escanea el QR del cliente. En Compra desde el asiento se asocia a la ubicaci\xF3n."
        },
        {
          title: "Actualiza estado",
          description: "El sistema actualiza en tiempo real: listo, entregado. Trazabilidad completa."
        }
      ]
    },
    organizer: {
      steps: [
        {
          title: "Configura tu evento",
          description: "Define puntos de venta, productos, precios y modalidades habilitadas."
        },
        {
          title: "Monitorea en tiempo real",
          description: "Visualiza ventas, inventario, pedidos activos y comportamiento de consumo."
        },
        {
          title: "Controla la operaci\xF3n",
          description: "Ajusta precios, activa promociones, gestiona stock desde el dashboard."
        },
        {
          title: "Analiza resultados",
          description: "Accede a reportes detallados, m\xE9tricas de rendimiento y data accionable."
        }
      ]
    }
  },
  benefits: {
    label: "Beneficios",
    title: "Resultados que",
    titleHighlight: "transforman tu evento",
    commercial: {
      title: "Comerciales",
      items: [
        {
          title: "+80% ventas por asistente",
          description: "Incrementa el consumo capturando ventas que antes se perd\xEDan en filas."
        },
        {
          title: "Momentos peak aprovechados",
          description: "Maximiza la venta en los momentos de mayor demanda del evento."
        },
        {
          title: "Mayor ticket promedio",
          description: "La compra digital sin fricci\xF3n incrementa naturalmente el valor por transacci\xF3n."
        }
      ]
    },
    experience: {
      title: "Experiencia del asistente",
      items: [
        {
          title: "-70% tiempo de espera",
          description: "Elimina las filas y la frustraci\xF3n. M\xE1s tiempo disfrutando, menos esperando."
        },
        {
          title: "Compra desde el celular",
          description: "Sin descargar apps. Acceso inmediato, pago r\xE1pido, retiro ordenado."
        },
        {
          title: "Entrega al asiento",
          description: "En estadios, suites y VIP, el consumo llega directamente a la ubicaci\xF3n del asistente."
        }
      ]
    },
    operational: {
      title: "Operativos",
      items: [
        {
          title: "Control total en tiempo real",
          description: "Centraliza pedidos, inventario y m\xE9tricas en un solo panel operativo."
        },
        {
          title: "Operaci\xF3n m\xE1s eficiente",
          description: "Menos personal en caja, mejor coordinaci\xF3n y trazabilidad completa."
        },
        {
          title: "Inventario inteligente",
          description: "Monitoreo de stock en vivo con alertas y capacidad de reacci\xF3n inmediata."
        }
      ]
    },
    technical: {
      title: "Tecnol\xF3gicos",
      items: [
        {
          title: "Sin infraestructura adicional",
          description: "No requiere t\xF3tems, cajas registradoras ni hardware especializado."
        },
        {
          title: "Implementaci\xF3n flexible",
          description: "Se adapta a cualquier recinto, formato de evento y volumen de asistentes."
        },
        {
          title: "Integraci\xF3n sin fricci\xF3n",
          description: "Compatible con tu operaci\xF3n actual. Implementaci\xF3n en d\xEDas, no meses."
        }
      ]
    }
  },
  industries: {
    label: "Industrias",
    title: "Dise\xF1ado para cada",
    titleHighlight: "tipo de recinto",
    subtitle: "Cada industria tiene desaf\xEDos \xFAnicos. Ronda Priv\xE9 se adapta con soluciones espec\xEDficas para maximizar resultados.",
    nightclubs: {
      title: "Nightclubs",
      description: "Optimiza la venta en barra y mesas VIP. Menos congesti\xF3n, m\xE1s rotaci\xF3n, mayor consumo por mesa.",
      problem: "Barras congestionadas, p\xE9rdida de ventas en momentos peak, dificultad para atender mesas VIP con agilidad.",
      solution: "Pedidos desde mesa o zona VIP directo al celular. Compra y Retira para reducir filas en barra. Dashboard con m\xE9tricas en vivo.",
      useCases: "Pedidos desde mesa VIP \u2022 Compra y Retira en barra principal \u2022 Promociones en tiempo real \u2022 Control de stock de botellas"
    },
    festivals: {
      title: "Festivales",
      description: "Mayor velocidad en puntos de alta demanda. Compra anticipada para reducir congesti\xF3n y planificar inventario.",
      problem: "Miles de asistentes, m\xFAltiples puntos de venta, filas interminables y p\xE9rdida masiva de ventas potenciales.",
      solution: "Compra y Retira en todos los puntos. Compra anticipada pre-evento. Inventario centralizado con alertas de stock.",
      useCases: "Compra anticipada de combos \u2022 Compra y Retira en barras m\xFAltiples \u2022 Inventario multi-punto \u2022 Reportes por zona"
    },
    stadiums: {
      title: "Estadios y Conciertos",
      description: "QR en asientos, suites y hospitality. Compra desde el asiento con entrega directa sin perder el espect\xE1culo.",
      problem: "Asistentes abandonan sus asientos para comprar y pierden el show. Suites y hospitality sin servicio \xE1gil.",
      solution: "QR en cada asiento o sector. Compra desde el celular con entrega al asiento. Compra y Retira para sectores generales.",
      useCases: "Delivery al asiento \u2022 QR por sector \u2022 Servicio en suites \u2022 Compra y Retira en cantinas \u2022 Compra anticipada"
    },
    bars: {
      title: "Bares y Venues",
      description: "Flujo de pedidos m\xE1s ordenado, operaci\xF3n eficiente y mayor rotaci\xF3n en noches de alta demanda.",
      problem: "Barras saturadas en horarios pico, errores en pedidos, falta de control de inventario y caja.",
      solution: "Pedidos desde QR en mesa o barra. Preparaci\xF3n ordenada por prioridad. Dashboard de ventas y stock en tiempo real.",
      useCases: "QR en mesas \u2022 Compra y Retira en barra \u2022 Control de stock en vivo \u2022 M\xE9tricas de consumo por hora"
    }
  },
  dashboard: {
    label: "Dashboard",
    title: "Control total.",
    titleHighlight: "Decisiones en tiempo real.",
    subtitle: "El panel de control que centraliza toda la operaci\xF3n de tu evento en una sola vista.",
    modules: [
      {
        title: "Estad\xEDsticas r\xE1pidas",
        description: "Ventas totales, transacciones, ticket promedio y tendencias al instante."
      },
      {
        title: "Gesti\xF3n de eventos",
        description: "Configura productos, precios, puntos de venta y modalidades por evento."
      },
      {
        title: "Inventario en vivo",
        description: "Stock actualizado en tiempo real con alertas de bajo inventario."
      },
      {
        title: "Monitoreo de ventas",
        description: "Visualiza ventas por producto, punto de venta, horario y tendencia."
      },
      {
        title: "Control de pedidos",
        description: "Seguimiento de cada pedido desde la compra hasta la entrega."
      }
    ],
    stats: {
      revenue: "$47,320",
      transactions: "1,847",
      avgTicket: "$25.60",
      revenueLabel: "Ventas totales",
      transactionsLabel: "Transacciones",
      avgTicketLabel: "Ticket promedio"
    }
  },
  socialProof: {
    label: "Testimonios",
    title: "Lo que dicen nuestros",
    titleHighlight: "clientes",
    testimonials: [
      {
        quote: "Ronda Priv\xE9 transform\xF3 completamente nuestra operaci\xF3n. Incrementamos las ventas un 65% y eliminamos las filas en barra.",
        author: "Carlos M.",
        role: "Director de Operaciones",
        company: "Arena Santiago"
      },
      {
        quote: "La compra desde el asiento en nuestras suites VIP elev\xF3 la experiencia a otro nivel. Los clientes no paran de elogiar el servicio.",
        author: "Mar\xEDa L.",
        role: "Gerente de Hospitalidad",
        company: "Estadio Nacional"
      }
    ]
  },
  cta: {
    label: "Comienza hoy",
    title: "Transforma la operaci\xF3n de tu evento",
    titleHighlight: "una venta menos",
    subtitle: "Agenda una demo personalizada y descubre c\xF3mo Ronda Priv\xE9 maximiza tus ventas sin infraestructura adicional.",
    benefits: [
      "Implementaci\xF3n en menos de 48 horas",
      "Sin hardware ni infraestructura adicional",
      "Soporte dedicado 24/7"
    ],
    form: {
      name: "Nombre completo",
      email: "Email corporativo",
      company: "Empresa u organizaci\xF3n",
      venueType: "Tipo de recinto",
      venueTypes: {
        nightclub: "Nightclub",
        festival: "Festival",
        stadium: "Estadio / Concierto",
        bar: "Bar / Venue",
        other: "Otro"
      },
      message: "Mensaje (opcional)",
      submit: "Solicitar demo",
      scheduling: "O agenda directamente una reuni\xF3n"
    },
    eyebrow: "Comienza hoy",
    titleStart: "Cada minuto en la fila es",
    sendEmail: "Mandar un mail"
  },
  events: {
    heroTitle: "Descubre",
    heroHighlight: "eventos activos",
    heroSubtitle: "Explora los eventos que ya utilizan Ronda Priv\xE9. Compra sin filas, retira al instante.",
    active: "Eventos activos",
    upcoming: "Pr\xF3ximos eventos",
    all: "Todos",
    features: {
      pickup: "Compra y Retira",
      seat: "Compra desde el asiento",
      preorder: "Compra anticipada"
    },
    viewEvent: "Ver evento",
    viewMenu: "Ver carta",
    vendors: "Puntos de venta",
    backToEvents: "Volver a eventos",
    searchPlaceholder: "Buscar por evento, venue o ciudad...",
    allCountries: "Todos los pa\xEDses",
    sortDate: "M\xE1s pr\xF3ximos",
    sortName: "A-Z",
    countOf: "{{count}} de {{total}} eventos",
    clearFilters: "Limpiar filtros",
    emptyTitle: "No se encontraron eventos",
    emptyBody: "No hay eventos que coincidan con tu b\xFAsqueda. Prueba con otros filtros o explora todos los eventos disponibles.",
    viewAll: "Ver todos los eventos",
    implementTitle: "\xBFQuieres implementar esto en tu evento?",
    implementSubtitle: "Conoce la plataforma Ronda Priv\xE9"
  },
  product: {
    heroTitle: "El producto que",
    heroHighlight: "elimina la fila",
    heroSubtitle: "Cuatro capacidades que trabajan juntas: tres formas de vender y una operaci\xF3n de barra y cocina hecha para el ritmo de un evento.",
    modesTitle: "Las cuatro capacidades",
    viewDetail: "Ver detalle",
    overview: "Vista general del producto",
    otherModesTitle: "Otras capacidades",
    stepsTitle: "C\xF3mo funciona, paso a paso",
    impactTitle: "Lo que cambia en tu operaci\xF3n",
    impactCta: "Te mostramos c\xF3mo se ve en tu recinto.",
    pickup: {
      title: "Compra y Retira",
      subtitle: "Tu p\xFAblico pide desde el celular y retira sin fila. Tu equipo despacha hasta 3x m\xE1s r\xE1pido.",
      seoDescription: "Compra y Retira en cuatro pasos: escanea el QR del comercio, elige de la carta, paga desde el celular y retira dando tu n\xFAmero de orden. Sin filas.",
      kitchenTeaser: {
        title: "Y en la barra, el pedido ya est\xE1 en pantalla",
        description: "El operador ve la comanda con su n\xFAmero de orden y marca listo. El cliente ve el cambio en su celular al instante.",
        link: "Ver c\xF3mo funciona la operaci\xF3n de barra y cocina",
        ticketLabel: "Comanda",
        action: "Marcar listo"
      },
      comparison: {
        before: "Operaci\xF3n tradicional",
        after: "Con Ronda Priv\xE9",
        rows: [
          { before: "El cliente hace fila para pedir y otra para pagar", after: "Pide desde donde est\xE1" },
          { before: "Cada punto de venta necesita terminal y caja", after: "Cero infraestructura extra" },
          { before: "El personal cobra en vez de preparar", after: "El personal solo prepara y entrega" },
          { before: "Los datos de consumo llegan al d\xEDa siguiente", after: "Datos en vivo durante el evento" }
        ]
      },
      otherModesIntro: "Los tres canales operan en el mismo evento, sobre la misma carta y el mismo panel.",
      validation: {
        label: "VALIDADO EN OPERACI\xD3N REAL",
        title: "Fiesta LOLA, Rancagua",
        detail: "Probado en sector general y \xE1rea VIP"
      },
      impact: [
        {
          value: "\u221285%",
          label: "Filas",
          note: "Sin t\xF3tems ni cajas: el pedido entra desde el celular."
        },
        {
          value: "+40%",
          label: "Ventas",
          note: "M\xE1s rondas por persona cuando pedir toma dos minutos."
        },
        {
          value: "3x",
          label: "Velocidad de servicio",
          note: "Tu equipo prepara en vez de cobrar."
        },
        {
          value: "0",
          label: "Infraestructura extra",
          note: "Funciona con los dispositivos que ya tienes."
        }
      ],
      steps: [
        {
          title: "Escanea el QR del comercio",
          description: "Cada comercio tiene su QR. No hay que descargar nada."
        },
        {
          title: "Explora la carta y elige",
          description: "Ve los productos disponibles y arma tu pedido desde el celular."
        },
        {
          title: "Paga",
          description: "Pago digital en segundos, sin efectivo ni terminal."
        },
        {
          title: "Sigue tu pedido y retira",
          description: "La pantalla se pone verde cuando tu pedido est\xE1 listo. Vas al punto de retiro, muestras tu n\xFAmero y listo.",
          note: "El organizador puede pedir adem\xE1s un c\xF3digo de 4 d\xEDgitos."
        }
      ],
      screens: {
        aria: "Simulaci\xF3n del flujo de Compra y Retira en el celular",
        scanTitle: "Escanea el QR de la barra",
        scanHint: "Apunta la c\xE1mara al c\xF3digo",
        barName: "Barra Central",
        barFloor: "4to piso",
        waitLabel: "Espera: 6 min",
        menuSearch: "Buscar en la carta\u2026",
        catAll: "Todos",
        catCocktails: "C\xF3cteles",
        popular: "Popular",
        item1Name: "Mojito",
        item1Desc: "Ron blanco, menta fresca, az\xFAcar",
        item1Price: "$8.000",
        item2Name: "Cerveza lager",
        item2Desc: "Lata 470 ml",
        item2Price: "$3.200",
        cartLabel: "Ver pedido",
        totalLabel: "Total",
        total: "$11.200",
        processingLabel: "Procesando pago\u2026",
        orderNumber: "A127",
        codeLabel: "C\xF3digo",
        codeValue: "7342",
        preparingBanner: "En preparaci\xF3n",
        readyBanner: "\xA1Tu pedido est\xE1 listo!",
        readyHint: "Pres\xE9ntalo en el punto de retiro"
      }
    },
    seat: {
      title: "Compra desde el asiento",
      subtitle: "Delivery directo a tu ubicaci\xF3n dentro del recinto",
      seoDescription: "Entrega en asiento: cada asiento tiene su QR, el pedido llega a la ubicaci\xF3n exacta y nadie se pierde parte del show por ir a la barra.",
      steps: [
        {
          title: "Escanea el QR del asiento",
          description: "Cada asiento, mesa o sector tiene un QR \xFAnico que identifica la ubicaci\xF3n."
        },
        {
          title: "Confirma tu ubicaci\xF3n",
          description: "El sistema detecta autom\xE1ticamente tu sector, fila y asiento."
        },
        {
          title: "Explora y compra",
          description: "Accede a la carta digital y realiza tu compra desde el celular."
        },
        {
          title: "Se genera el pedido",
          description: "El pedido se crea con un c\xF3digo \xFAnico asociado a tu ubicaci\xF3n."
        },
        {
          title: "Preparaci\xF3n en tiempo real",
          description: "El pedido se prepara y puedes seguir su estado en vivo."
        },
        {
          title: "Entrega en tu asiento",
          description: "El consumo se entrega directamente en tu ubicaci\xF3n."
        }
      ]
    },
    preorder: {
      title: "Compra anticipada",
      subtitle: "Compra antes del evento, retira el d\xEDa del show",
      seoDescription: "Compra anticipada: el p\xFAblico compra d\xEDas antes del evento y retira el d\xEDa del show con un QR, sin fila y con la demanda proyectada de antemano.",
      steps: [
        {
          title: "Compra antes del evento",
          description: "Accede a la carta del evento d\xEDas antes y selecciona tus productos."
        },
        {
          title: "Paga por adelantado",
          description: "Realiza el pago con anticipaci\xF3n y asegura tu consumo."
        },
        {
          title: "Recibe tu QR",
          description: "Un c\xF3digo QR se genera como comprobante de tu compra anticipada."
        },
        {
          title: "El d\xEDa del evento, retira",
          description: "Presenta tu QR en el punto de retiro y recibe tu pedido sin esperar."
        }
      ]
    },
    kitchen: {
      title: "Operaci\xF3n de barra y cocina",
      subtitle: "Flujo operativo dise\xF1ado para velocidad y control",
      seoDescription: "Operaci\xF3n de barra y cocina: cada pedido llega ordenado por producto, cliente o ubicaci\xF3n, con estados en vivo y control de lo que se prepara.",
      description: "Cuando entra un pedido, el equipo operativo visualiza el detalle completo. El personal de barra o cocina ve cada pedido por producto, cliente o ubicaci\xF3n. El sistema permite iniciar preparaci\xF3n, actualizar estados y mantener trazabilidad completa.",
      statuses: [
        "Recibido",
        "En preparaci\xF3n",
        "Listo",
        "Entregado"
      ],
      benefits: [
        "Control total del flujo",
        "Mayor velocidad de preparaci\xF3n",
        "Coordinaci\xF3n entre equipos",
        "Trazabilidad de cada pedido"
      ]
    },
    ctaTitle: "\xBFListo para transformar tu operaci\xF3n?"
  },
  faq: {
    heroTitle: "Preguntas",
    heroHighlight: "frecuentes",
    heroSubtitle: "Todo lo que necesitas saber sobre Ronda Priv\xE9 y c\xF3mo funciona para tu evento.",
    categories: {
      general: "General",
      attendees: "Para asistentes",
      organizers: "Para organizadores",
      technical: "T\xE9cnico"
    },
    all: "Todas",
    q1: "\xBFSe requiere infraestructura adicional?",
    a1: "No. Ronda Priv\xE9 funciona 100% desde el celular de los asistentes. No se requieren t\xF3tems, cajas registradoras ni hardware adicional. Solo necesitas conexi\xF3n a internet en el recinto.",
    q2: "\xBFSe necesitan t\xF3tems?",
    a2: "No. A diferencia de otras soluciones, Ronda Priv\xE9 elimina la necesidad de t\xF3tems o terminales de autoservicio. Todo funciona desde el dispositivo m\xF3vil del asistente.",
    q3: "\xBFCu\xE1nto tiempo toma implementarlo?",
    a3: "La implementaci\xF3n es r\xE1pida y flexible. En la mayor\xEDa de los casos, un evento puede estar operativo en menos de 48 horas. Nuestro equipo acompa\xF1a todo el proceso.",
    q4: "\xBFSe integra con mi POS actual?",
    a4: "S\xED. Ronda Priv\xE9 se integra de forma flexible con los sistemas de punto de venta m\xE1s utilizados en la industria. Nuestro equipo t\xE9cnico configura la integraci\xF3n seg\xFAn tu infraestructura.",
    q5: "\xBFC\xF3mo funciona para barra y cocina?",
    a5: "El personal recibe los pedidos en una pantalla o dispositivo dedicado. Cada pedido muestra los productos, la ubicaci\xF3n del cliente y el estado. El equipo puede marcar estados como recibido, en preparaci\xF3n, listo y entregado.",
    q6: "\xBFC\xF3mo se implementa en un evento?",
    a6: "Configuramos tu evento en la plataforma: puntos de venta, productos, precios y modalidades. Generamos los QR necesarios y capacitamos a tu equipo. El d\xEDa del evento, todo est\xE1 listo para operar.",
    q7: "\xBFSe puede usar en recintos con sectores o asientos?",
    a7: "S\xED. La modalidad de compra desde el asiento est\xE1 dise\xF1ada espec\xEDficamente para estadios, suites, hospitality y cualquier recinto con sectores identificados.",
    q8: "\xBFSe puede personalizar por evento?",
    a8: "Completamente. Cada evento puede tener su propia carta, precios, puntos de venta, modalidades habilitadas y configuraci\xF3n operativa.",
    q9: "\xBFC\xF3mo se controla el inventario?",
    a9: "El dashboard muestra el inventario en tiempo real por producto y punto de venta. Incluye alertas de bajo stock y capacidad de ajustar cantidades al instante.",
    q10: "\xBFQu\xE9 pasa si hay alta demanda?",
    a10: "La plataforma est\xE1 dise\xF1ada para escalar. Soporta miles de transacciones concurrentes sin degradar el rendimiento. La arquitectura cloud garantiza estabilidad en picos de demanda.",
    q11: "\xBFFunciona con m\xFAltiples puntos de venta?",
    a11: "S\xED. Puedes configurar tantos puntos de venta como necesites, cada uno con su propia carta, inventario y equipo operativo. Todo centralizado en un solo dashboard.",
    q12: "\xBFQu\xE9 m\xE9todos de pago aceptan?",
    a12: "Aceptamos tarjetas de cr\xE9dito, d\xE9bito y los principales medios de pago digitales disponibles en cada mercado. La integraci\xF3n de pagos es segura y cumple con est\xE1ndares internacionales.",
    q13: "\xBFPermite compra anticipada?",
    a13: "S\xED. La compra anticipada permite que los asistentes compren antes del evento, paguen por adelantado y retiren el d\xEDa del show presentando su QR. Esto mejora la planificaci\xF3n operativa y reduce la congesti\xF3n."
  },
  glossary: {
    heroTitle: "Glosario",
    heroHighlight: "del rubro de eventos y venues",
    heroSubtitle: "Definiciones de los conceptos que usamos en Ronda Priv\xE9 y que escuchar\xE1s en el sector.",
    categories: {
      sales: "Modalidades de venta",
      venue: "Operaci\xF3n de venue",
      tech: "Tecnolog\xEDa",
      spaces: "Tipos de recinto",
      metrics: "M\xE9tricas del negocio"
    },
    terms: {
      "compra-anticipada": {
        term: "Compra anticipada",
        definition: "Modalidad de venta donde el cliente compra y paga su consumo d\xEDas o semanas antes del evento. El d\xEDa del evento activa tu compra y ret\xEDrala sin hacer filas. Permite al organizador planificar inventario con anticipaci\xF3n."
      },
      "compra-y-retiro": {
        term: "Compra y Retira",
        definition: "Modalidad donde el cliente compra desde su celular durante el evento y retira el pedido en un punto de venta cuando est\xE1 listo. Funciona como fila digital: no requiere esperar en una l\xEDnea f\xEDsica."
      },
      "entrega-en-asiento": {
        term: "Entrega en asiento",
        definition: "Modalidad para eventos con asientos identificados (estadios, suites, palcos, hospitality). El cliente escanea el QR de su ubicaci\xF3n, compra desde el celular y recibe el pedido directamente en su asiento o mesa, sin moverse."
      },
      "fila-digital": {
        term: "Fila digital",
        definition: "Sistema que reemplaza la fila f\xEDsica por una cola gestionada digitalmente. El cliente compra desde su celular, recibe un n\xFAmero de orden y se acerca al punto de retiro solo cuando el pedido est\xE1 listo."
      },
      "numero-de-orden": {
        term: "N\xFAmero de orden",
        definition: "Identificador \xFAnico que recibe el cliente al concretar la compra. Sirve para retirar el pedido y, seg\xFAn la configuraci\xF3n del organizador, puede pedirse junto con un c\xF3digo de verificaci\xF3n adicional."
      },
      "punto-de-venta": {
        term: "Punto de venta (POS)",
        definition: "Espacio f\xEDsico o sistema digital donde se concreta una venta. En eventos los puntos de venta tradicionales incluyen barras, cajas registradoras y kioscos. Una plataforma como Ronda Priv\xE9 funciona como POS digital sin hardware dedicado."
      },
      "totem-de-autoservicio": {
        term: "T\xF3tem de autoservicio",
        definition: "Terminal f\xEDsico ubicado en el recinto donde el cliente arma y paga su pedido. Requiere infraestructura (pantalla, lector de tarjeta, mantenci\xF3n) y ocupa espacio. Es la alternativa que la compra desde el celular reemplaza."
      },
      "carta-digital": {
        term: "Carta digital",
        definition: "Men\xFA de productos accesible desde el celular del cliente. Permite actualizar precios, agregar promociones y desactivar productos en stock cero sin imprimir cartas f\xEDsicas."
      },
      "inventario-tiempo-real": {
        term: "Inventario en tiempo real",
        definition: "Control de stock que se actualiza con cada venta concretada. Permite ver el inventario disponible por producto y por punto de venta, detectar quiebres antes de que ocurran y reabastecer con tiempo."
      },
      dashboard: {
        term: "Panel de control (dashboard)",
        definition: "Interfaz para el organizador del evento que concentra m\xE9tricas de ventas, pedidos activos, inventario y configuraci\xF3n operativa. Centraliza la operaci\xF3n en una sola vista."
      },
      pwa: {
        term: "PWA (Progressive Web App)",
        definition: "Aplicaci\xF3n que corre en el navegador del celular pero se comporta como una app nativa: carga r\xE1pida, posibilidad de funcionar sin conexi\xF3n por momentos, se puede agregar al home screen. No requiere descarga desde una tienda de apps."
      },
      qr: {
        term: "C\xF3digo QR",
        definition: "Imagen cuadrada que codifica un link o dato. El cliente la escanea con la c\xE1mara del celular y abre directamente la carta del evento o el pedido. Reemplaza la necesidad de descargar apps o tipear URLs."
      },
      "modo-cache": {
        term: "Modo cach\xE9 (offline-first)",
        definition: "Capacidad de la plataforma para seguir operando ante una p\xE9rdida moment\xE1nea de conexi\xF3n a internet. Las acciones se guardan localmente y se sincronizan en cuanto vuelve la se\xF1al."
      },
      trazabilidad: {
        term: "Trazabilidad de pedido",
        definition: "Registro del estado de cada pedido desde la compra hasta la entrega: recibido, en preparaci\xF3n, listo, entregado. Permite resolver discusiones con clientes y medir tiempos reales de preparaci\xF3n."
      },
      cloud: {
        term: "Infraestructura en la nube (cloud)",
        definition: "Servidores externos \u2014en el caso de Ronda Priv\xE9, AWS\u2014 que procesan los pedidos sin que el venue necesite hardware local. Garantiza disponibilidad ante picos de demanda y elimina el riesgo de fallo por equipos f\xEDsicos."
      },
      venue: {
        term: "Venue / Recinto",
        definition: "Lugar f\xEDsico donde se realiza un evento u opera un negocio del rubro hospitalidad. Incluye desde estadios y festivales hasta bares, restaurantes y coffee shops."
      },
      suite: {
        term: "Suite",
        definition: "Espacio privado dentro de un estadio o arena, generalmente con servicio de hospitalidad incluido. Cuenta con visi\xF3n directa al evento, mobiliario propio y atenci\xF3n personalizada."
      },
      palco: {
        term: "Palco",
        definition: "Sector elevado y privado dentro de un teatro, estadio o recinto. Se diferencia de la grada general en privacidad y servicio. Puede ser corporativo o privado."
      },
      hospitality: {
        term: "Hospitality",
        definition: "Servicio premium dentro de un evento que incluye comida, bebidas y atenci\xF3n personalizada. Suele venderse como paquete adicional a la entrada general y opera con din\xE1mica distinta a la barra masiva."
      },
      festival: {
        term: "Festival",
        definition: "Evento masivo, generalmente al aire libre, con uno o varios escenarios musicales y duraci\xF3n de uno a varios d\xEDas. Se caracteriza por alta concurrencia simult\xE1nea y m\xFAltiples puntos de venta de consumo."
      },
      "coffee-shop": {
        term: "Coffee shop / Local peque\xF1o",
        definition: "Establecimiento de hospitalidad con flujo constante de clientes pero menor escala que un evento masivo. Opera durante todo el d\xEDa y maneja una rotaci\xF3n alta de pedidos chicos."
      },
      "ticket-promedio": {
        term: "Ticket promedio",
        definition: "Valor monetario promedio de cada transacci\xF3n durante un evento. Se calcula dividiendo el ingreso total por la cantidad de transacciones. Es uno de los KPI principales para evaluar el rendimiento de un punto de venta."
      },
      "tiempo-de-espera": {
        term: "Tiempo de espera",
        definition: "Minutos que un cliente pasa entre pedir y recibir su consumo. En eventos masivos puede llegar a 15-30 minutos en barra f\xEDsica; con compra digital baja t\xEDpicamente a 2-3 minutos."
      },
      "rotacion-de-barra": {
        term: "Rotaci\xF3n de barra",
        definition: "Cantidad de clientes que un punto de venta puede atender por hora. Una rotaci\xF3n alta significa m\xE1s ventas en el mismo espacio f\xEDsico. Es el indicador clave para dimensionar la operaci\xF3n de un evento."
      },
      "tasa-de-conversion": {
        term: "Tasa de conversi\xF3n",
        definition: "Porcentaje de asistentes a un evento que efectivamente compraron consumo. Una conversi\xF3n baja indica que asistentes potenciales no llegaron a comprar \u2014 usualmente por filas largas o falta de stock."
      }
    }
  },
  insights: {
    heroTitle: "Insights &",
    heroHighlight: "tendencias",
    heroSubtitle: "Ideas, estrategias y mejores pr\xE1cticas para la industria de eventos y hospitalidad.",
    categories: {
      all: "Todos",
      trends: "Tendencias",
      cases: "Casos de uso",
      product: "Producto",
      industry: "Industria"
    },
    readMore: "Leer m\xE1s",
    minRead: "min de lectura",
    backToInsights: "Volver a Insights",
    detailCtaTitle: "\xBFQuieres ver estas ideas funcionando en tu evento?",
    detailCtaButton: "Solicitar una demo",
    post1: {
      title: "C\xF3mo incrementar las ventas de F&B en eventos masivos",
      excerpt: "Estrategias comprobadas para maximizar el consumo por asistente y capturar ventas que se pierden en filas.",
      intro: "En un evento masivo, la venta de alimentos y bebidas puede representar una parte importante del ingreso total. Sin embargo, gran parte de esa venta se pierde por un motivo evitable: la fricci\xF3n. Filas largas, puntos de venta saturados y asistentes que prefieren no perderse el show antes que esperar por una bebida.",
      sections: [
        { heading: "El costo invisible de las filas", body: "Cuando la fila supera los pocos minutos, una parte de los asistentes simplemente desiste. Esa venta no se recupera: el consumo en eventos es por impulso y depende del momento. Si el impulso pasa, la compra no ocurre.\n\nAdem\xE1s, la demanda no se distribuye pareja: se concentra en picos \u2014 el entretiempo, el cambio de artista, los minutos previos al show principal. Es justo ah\xED donde la capacidad de atenci\xF3n colapsa y m\xE1s ventas se pierden." },
        { heading: "Convertir cada ubicaci\xF3n en un punto de venta", body: "La forma m\xE1s directa de vender m\xE1s no es abrir m\xE1s barras, sino multiplicar los puntos de compra sin infraestructura extra. Con compra desde el celular v\xEDa QR, cada asiento, mesa o sector se convierte en un punto de venta.\n\nEl asistente pide desde su ubicaci\xF3n y retira cuando el pedido est\xE1 listo, o lo recibe directamente en su asiento. La barra deja de ser el \xFAnico canal y la demanda se reparte." },
        { heading: "Adelantar la venta con compra anticipada", body: "La compra anticipada permite capturar ingresos d\xEDas o semanas antes del evento: el asistente paga por adelantado y el d\xEDa del evento solo retira presentando su QR.\n\nPara el organizador significa flujo de caja anticipado, demanda conocida y menos congesti\xF3n en los momentos de mayor presi\xF3n operativa." },
        { heading: "Medir en tiempo real para reaccionar a tiempo", body: "Sin datos en vivo, los problemas se descubren cuando ya costaron ventas. Un dashboard con ventas e inventario en tiempo real permite reasignar staff hacia los puntos con m\xE1s demanda, reponer stock antes del quiebre y ajustar la operaci\xF3n durante el evento, no despu\xE9s." }
      ]
    },
    post2: {
      title: "El futuro de la tecnolog\xEDa F&B en eventos",
      excerpt: "Tendencias globales en digitalizaci\xF3n de la venta de alimentos y bebidas en la industria de eventos.",
      intro: "La venta de alimentos y bebidas en eventos est\xE1 cambiando r\xE1pido. Lo que hace unos a\xF1os era efectivo y caja registradora hoy es pago digital, pedidos por QR y datos en tiempo real. Estas son las tendencias que est\xE1n marcando el rumbo de la industria.",
      sections: [
        { heading: "Del efectivo al pago digital", body: "El pago digital dej\xF3 de ser un diferenciador para convertirse en la expectativa base. En la regi\xF3n, la adopci\xF3n de billeteras digitales y pagos sin contacto crece sostenidamente, y los eventos siguen la misma curva: menos efectivo circulando significa operaciones m\xE1s r\xE1pidas, menos errores de caja y trazabilidad completa de cada venta." },
        { heading: "Web apps en lugar de descargas", body: "Las apps nativas tienen un problema estructural en eventos: nadie quiere descargar una aplicaci\xF3n para comprar una bebida. Las PWA (aplicaciones web progresivas) eliminan esa fricci\xF3n \u2014 el asistente escanea un QR y compra de inmediato desde el navegador, sin descargas ni registro extenso.\n\nPara el organizador, eso se traduce en tasas de adopci\xF3n mucho m\xE1s altas que las de cualquier app que exija instalaci\xF3n." },
        { heading: "Los datos de consumo como activo", body: "Cada pedido digital genera informaci\xF3n: qu\xE9 se vende, a qu\xE9 hora, en qu\xE9 sector y a qu\xE9 precio. Ese historial permite planificar los pr\xF3ximos eventos con demanda real en vez de intuici\xF3n: cu\xE1nto stock cargar, d\xF3nde ubicar los puntos de venta y qu\xE9 productos empujar.\n\nLos organizadores que acumulan estos datos evento tras evento toman decisiones que la competencia todav\xEDa adivina." },
        { heading: "Hacia una operaci\xF3n sin fricci\xF3n", body: "La direcci\xF3n es clara: menos filas, menos hardware y m\xE1s integraci\xF3n. La compra anticipada conectada al ticketing, la entrega en el asiento y el inventario sincronizado entre puntos de venta apuntan a lo mismo \u2014 que comprar dentro de un evento sea tan simple como comprar en cualquier tienda digital." }
      ]
    },
    post3: {
      title: "C\xF3mo reducir filas en estadios: caso de estudio",
      excerpt: "An\xE1lisis de c\xF3mo la implementaci\xF3n de compra digital redujo un 70% los tiempos de espera en un estadio.",
      intro: "Los estadios concentran uno de los desaf\xEDos operativos m\xE1s dif\xEDciles del F&B: decenas de miles de personas que quieren comprar en la misma ventana de minutos. Este an\xE1lisis recorre qu\xE9 pasa cuando se implementa compra digital por sectores y qu\xE9 resultados se pueden esperar.",
      sections: [
        { heading: "El punto de partida", body: "El patr\xF3n se repite en la mayor\xEDa de los estadios: la venta se concentra en el entretiempo y los cortes del espect\xE1culo. En esos minutos, las filas superan la capacidad de atenci\xF3n, buena parte del p\xFAblico desiste y la venta por asistente queda muy por debajo de su potencial." },
        { heading: "Qu\xE9 se implement\xF3", body: "La implementaci\xF3n combin\xF3 dos modalidades: compra desde el asiento para sectores premium \u2014 el asistente escanea el QR de su ubicaci\xF3n y recibe el pedido donde est\xE1 \u2014 y Compra y Retira para el resto del recinto, con puntos de retiro diferenciados por sector para repartir el flujo de gente.\n\nNo se instal\xF3 infraestructura adicional: la operaci\xF3n corre sobre los puntos de venta existentes y los celulares de los propios asistentes." },
        { heading: "Los resultados", body: "Con la compra digital operando, los tiempos de espera se redujeron en torno al 70%: el pedido se prepara mientras el asistente sigue en su asiento, y el retiro toma segundos en lugar de minutos de fila.\n\nEl efecto comercial acompa\xF1a: al eliminar la barrera de la espera, m\xE1s asistentes compran y aumenta la frecuencia de pedidos durante el evento." },
        { heading: "Aprendizajes para otras implementaciones", body: "Tres factores marcaron la diferencia: se\xF1al\xE9tica clara para que el p\xFAblico entienda el flujo de retiro, capacitaci\xF3n breve del staff en el nuevo flujo de preparaci\xF3n, y una carta acotada que mantiene los tiempos de preparaci\xF3n estables incluso en los picos de demanda." }
      ]
    },
    post4: {
      title: "Gesti\xF3n de inventario en tiempo real para eventos",
      excerpt: "Mejores pr\xE1cticas para controlar stock, evitar quiebres y optimizar la operaci\xF3n durante un evento.",
      intro: "En un evento no existe 'reponer ma\xF1ana': el stock que se quiebra durante el show es venta perdida que no vuelve. Por eso la gesti\xF3n de inventario en eventos tiene reglas propias, y la visibilidad en tiempo real es la principal.",
      sections: [
        { heading: "Por qu\xE9 el inventario se quiebra en eventos", body: "Un evento comprime la demanda de una semana de operaci\xF3n normal en pocas horas. Con planillas o conteo manual, el organizador se entera del quiebre cuando el producto ya no est\xE1 \u2014 y cada minuto sin stock en un punto de alta demanda es ingreso que se evapora.\n\nEl problema inverso tambi\xE9n cuesta caro: el sobrestock termina en merma o capital inmovilizado." },
        { heading: "Visibilidad en vivo por punto de venta", body: "El inventario en tiempo real muestra qu\xE9 queda de cada producto en cada barra o punto de venta, actualizado con cada pedido. Eso convierte el stock en una variable que se gestiona durante el evento: si una barra agota un producto, se redistribuye desde otra antes de perder ventas." },
        { heading: "Alertas y decisiones durante el show", body: "Los umbrales de alerta permiten actuar antes del quiebre: cuando un producto baja de cierto nivel, el equipo lo sabe al instante. Las decisiones dejan de depender de que alguien 'se d\xE9 cuenta' \u2014 el sistema avisa, el equipo ejecuta." },
        { heading: "Lo que queda despu\xE9s del evento", body: "Al cierre, los datos cuentan la historia completa: qu\xE9 se vendi\xF3, a qu\xE9 ritmo, d\xF3nde hubo quiebres y cu\xE1nta merma qued\xF3. Con esa base, el siguiente evento se planifica con demanda real: compras m\xE1s ajustadas, mejor distribuci\xF3n entre puntos de venta y menos capital inmovilizado." }
      ]
    },
    post5: {
      title: "Innovaci\xF3n en nightclubs: la nueva era de la venta digital",
      excerpt: "C\xF3mo los nightclubs m\xE1s exclusivos est\xE1n transformando la experiencia de compra con tecnolog\xEDa m\xF3vil.",
      intro: "En un nightclub, la experiencia es el producto. Y pocas cosas da\xF1an m\xE1s la experiencia que pasar veinte minutos tratando de pedir un trago en una barra saturada. Los clubes m\xE1s exclusivos lo entendieron y est\xE1n redise\xF1ando la venta con tecnolog\xEDa m\xF3vil.",
      sections: [
        { heading: "La barra como cuello de botella", body: "La barra concentra toda la venta del club en pocos metros: en horas punta, la espera crece, el cliente se frustra y consume menos. Cada minuto en la fila es un minuto fuera de la pista \u2014 y una ronda que quiz\xE1s no se pide." },
        { heading: "Mesas y VIP: servicio sin interrupciones", body: "El QR por mesa cambia la din\xE1mica del servicio: el grupo pide desde el celular y el pedido llega a la mesa, sin que nadie tenga que ir a la barra ni interceptar a un garz\xF3n.\n\nEn zonas VIP el efecto es mayor: el servicio se siente premium precisamente porque no exige esfuerzo, y la mesa mantiene su consumo activo durante toda la noche." },
        { heading: "Rotaci\xF3n y ticket promedio", body: "Menos espera se traduce directo en m\xE1s rondas por noche. Cuando pedir toma segundos, la frecuencia de consumo sube y el ticket promedio por mesa crece \u2014 sin presi\xF3n comercial, solo eliminando la fricci\xF3n que antes frenaba la compra." },
        { heading: "Qu\xE9 mirar al elegir tecnolog\xEDa para un club", body: "Tres criterios pr\xE1cticos: que no exija hardware adicional ni descargas de apps, que funcione de forma estable en condiciones reales de un club \u2014 poca luz, mucha gente, se\xF1al irregular \u2014 y que entregue datos por mesa y por producto para gestionar el negocio, no solo cobrar." }
      ]
    },
    post6: {
      title: "Compra anticipada: la estrategia que maximiza ingresos",
      excerpt: "Por qu\xE9 la venta pre-evento es la herramienta m\xE1s poderosa para aumentar previsibilidad y revenue.",
      intro: "De las tres modalidades de venta digital en eventos, la compra anticipada es la que m\xE1s impacto tiene en la previsibilidad del negocio: convierte demanda futura en ingreso presente y en informaci\xF3n para planificar.",
      sections: [
        { heading: "Qu\xE9 es y c\xF3mo funciona", body: "La compra anticipada permite que el asistente compre su consumo d\xEDas o semanas antes del evento, junto con la decisi\xF3n de asistir. El d\xEDa del evento, solo presenta su QR y retira \u2014 sin filas ni pagos en el recinto." },
        { heading: "Ingresos antes de abrir las puertas", body: "El efecto financiero es inmediato: una parte de la venta del evento ingresa por adelantado, mejora el flujo de caja y reduce la dependencia de lo que pase la noche del show. Para eventos con costos de producci\xF3n altos, ese adelanto puede financiar parte de la operaci\xF3n." },
        { heading: "Planificar con demanda real", body: "Cada compra anticipada es un dato de demanda confirmada: cu\xE1ntas personas van a consumir, qu\xE9 productos y en qu\xE9 volumen. Con esa informaci\xF3n, el stock y el staff se dimensionan sobre demanda real en lugar de estimaciones \u2014 menos quiebres, menos merma y una operaci\xF3n m\xE1s ajustada." },
        { heading: "C\xF3mo comunicarla para que funcione", body: "La compra anticipada rinde cuando se integra a la comunicaci\xF3n del evento: ofrecerla en el mismo momento de la compra de la entrada, recordarla en los d\xEDas previos y darle un incentivo concreto \u2014 conveniencia, beneficios o acceso preferente al retiro. Mientras m\xE1s natural es el paso de 'ya tengo mi entrada' a 'ya tengo mi primera ronda', mejor funciona." }
      ]
    }
  },
  contact: {
    heroTitle: "Hablemos de tu",
    heroHighlight: "pr\xF3ximo evento",
    heroSubtitle: "Agenda una demo personalizada y descubre c\xF3mo Ronda Priv\xE9 transforma la operaci\xF3n de tu evento.",
    formTitle: "Solicita una demo",
    formSubtitle: "Completa el formulario y nuestro equipo te contactar\xE1 en menos de 24 horas.",
    successTitle: "\xA1Mensaje enviado!",
    successMessage: "Nuestro equipo te contactar\xE1 en menos de 24 horas para coordinar tu demo personalizada.",
    sending: "Enviando...",
    errorMessage: "Ocurri\xF3 un error al enviar el mensaje. Por favor intenta nuevamente."
  },
  footer: {
    tagline: "La plataforma que transforma la venta de alimentos y bebidas en eventos de alta demanda.",
    productTitle: "Producto",
    resourcesTitle: "Recursos",
    contactTitle: "Contacto",
    solutions: "Soluciones",
    industries: "Industrias",
    howItWorks: "C\xF3mo funciona",
    benefits: "Beneficios",
    events: "Eventos",
    insights: "Insights",
    faq: "FAQ",
    glossary: "Glosario",
    contact: "Contacto",
    scheduleDemo: "Agendar demo",
    rights: "Todos los derechos reservados.",
    privacy: "Privacidad",
    terms: "T\xE9rminos"
  },
  common: {
    learnMore: "Saber m\xE1s",
    contactUs: "Cont\xE1ctanos",
    backToHome: "Volver al inicio",
    viewAll: "Ver todos",
    close: "Cerrar",
    loading: "Cargando...",
    notFound: "P\xE1gina no encontrada",
    notFoundMessage: "La p\xE1gina que buscas no existe o fue movida.",
    goHome: "Ir al inicio"
  },
  benefitsSummary: {
    label: "Beneficios",
    titleStart: "Dise\xF1ado para que todo",
    titleHighlight: "fluya",
    subtitle: "M\xE1s ventas, mejor experiencia y control total. Sin fricci\xF3n, sin filas, sin l\xEDmites.",
    cards: {
      sales: {
        title: "M\xE1s ventas, menos fricci\xF3n",
        description: "Convierte cada interacci\xF3n en una oportunidad de compra."
      },
      experience: {
        title: "Experiencia sin interrupciones",
        description: "Tus asistentes viven el evento, no las filas."
      },
      control: {
        title: "Control total en tiempo real",
        description: "Datos claros y actualizados para tomar mejores decisiones."
      },
      scale: {
        title: "Escalable a todo el recinto",
        description: "Una soluci\xF3n robusta que se adapta a cualquier evento y crece contigo."
      }
    },
    mocks: {
      salesLabel: "Ventas en vivo",
      passTitle: "Pase digital",
      passReady: "\n",
      dashboardTitle: "Resumen del evento",
      dashboardToday: "Hoy",
      dashboardSales: "Ventas",
      dashboardOrders: "Pedidos",
      dashboardProducts: "Vendidos"
    }
  },
  seo: {
    default: {
      title: "Ronda Priv\xE9 | Tecnolog\xEDa premium para eventos y venues",
      description: "Plataforma m\xF3vil para eventos y venues: compra anticipada, entrega al asiento y Compra y Retira. Sin filas ni t\xF3tems."
    },
    home: {
      title: "Elimina la espera y maximiza las ventas en tu venue",
      description: "Compra desde el celular en festivales, estadios y clubes. Menos filas, m\xE1s ticket promedio, control en tiempo real."
    },
    events: {
      title: "Eventos activos",
      description: "Eventos en vivo donde Ronda Priv\xE9 est\xE1 operando. Compra anticipada, entrega al asiento y Compra y Retira."
    },
    eventDetail: {
      title: "Evento",
      description: "Compra desde el celular antes y durante el show, sin filas ni t\xF3tems.",
      descriptionWithName: "{{name}} en Ronda Priv\xE9. Compra desde el celular antes y durante el show \u2014 sin filas, sin t\xF3tems."
    },
    product: {
      title: "Producto",
      description: "Las cuatro capacidades de Ronda Priv\xE9: compra anticipada, entrega en asiento, Compra y Retira y operaci\xF3n de barra y cocina."
    },
    industries: {
      title: "Soluciones por industria",
      description: "C\xF3mo Ronda Priv\xE9 se adapta a festivales, estadios, nightclubs, bares y venues. Casos por tipo de recinto."
    },
    howItWorks: {
      title: "C\xF3mo funciona",
      description: "C\xF3mo funciona Ronda Priv\xE9 para asistentes, equipo de cocina y organizadores. Flujo end-to-end de compra, preparaci\xF3n y control de pedidos."
    },
    benefits: {
      title: "Beneficios",
      description: "M\xE1s ventas, mejor experiencia y control total. Beneficios comerciales, operativos, t\xE9cnicos y de experiencia con Ronda Priv\xE9."
    },
    insights: {
      title: "Insights",
      description: "Tendencias, casos de uso y novedades sobre comercio m\xF3vil en eventos y venues. Lecturas para organizadores y operadores."
    },
    faq: {
      title: "Preguntas frecuentes",
      description: "Resolvemos las preguntas m\xE1s comunes sobre Ronda Priv\xE9: c\xF3mo se implementa, qu\xE9 necesita el venue, c\xF3mo se cobra, integraciones y m\xE1s."
    },
    glossary: {
      title: "Glosario del rubro de eventos y venues",
      description: "Definiciones de los conceptos del sector de eventos y hospitalidad: compra anticipada, entrega en asiento, POS, PWA, hospitality, suite y m\xE1s."
    },
    contact: {
      title: "Contacto",
      description: "Hablemos de tu evento o venue. Solicita una demo personalizada de Ronda Priv\xE9 y armamos juntos el setup que necesitas."
    }
  },
  eventsData: {
    "estereo-picnic-2026": {
      date: "28-30 Marzo 2026",
      country: "Colombia",
      description: "El festival de m\xFAsica m\xE1s grande de Colombia con artistas internacionales.",
      badgeText: "M\xE1s vendido"
    },
    "copa-libertadores-2026": {
      date: "15 Noviembre 2026",
      country: "Argentina",
      description: "La gran final de la Copa Libertadores de Am\xE9rica.",
      badgeText: "Todas las funciones"
    },
    "tomorrowland-winter-2026": {
      date: "14-21 Marzo 2026",
      country: "Francia",
      description: "La edici\xF3n invernal del festival m\xE1s grande del mundo."
    },
    "club-prive-madrid": {
      date: "Todos los fines de semana",
      country: "Espa\xF1a",
      description: "La experiencia nocturna m\xE1s exclusiva de Madrid.",
      badgeText: "VIP Exclusivo"
    },
    "tech-summit-2026": {
      date: "3-5 Junio 2026",
      country: "",
      description: "El evento de tecnolog\xEDa e innovaci\xF3n m\xE1s importante."
    },
    "lollapalooza-chile-2026": {
      date: "14-16 Marzo 2026",
      country: "Chile",
      description: "El festival Lollapalooza llega a Chile con lineup internacional.",
      badgeText: "Favorito"
    }
  },
  eventCategories: {
    festival: "Festival",
    concert: "Concierto",
    nightclub: "Nightclub",
    conference: "Conferencia",
    bar: "Bar"
  },
  eventFeatures: {
    preorder: "Compra anticipada",
    seat: "Compra desde el asiento",
    pickup: "Compra y Retira"
  },
  formatos: {
    channels: {
      pickup: "Compra y Retira",
      seat: "Desde el asiento",
      table: "Desde la mesa",
      preorder: "Anticipada"
    }
  },
  eventosActivos: {
    eyebrow: "Soluciones",
    title: "Dise\xF1ado para eventos a cualquier escala",
    subtitle: "Festivales, estadios, clubs y bares. La plataforma se adapta a cualquier formato y crece junto a tu evento.",
    ctaPrimary: "Hablemos de tu evento",
    ctaSecondary: "o explorar eventos donde estamos \u2192"
  },
  plataforma: {
    heading: "Una plataforma. Tres formas de eliminar las filas.",
    subtitle: "La forma m\xE1s r\xE1pida, segura y c\xF3moda de disfrutar cada momento.",
    toggleShow: "Ver c\xF3mo funciona",
    toggleHide: "Ocultar pasos",
    ctaQuestion: "\xBFQuieres esto en tu pr\xF3ximo evento?",
    products: {
      preorder: {
        label: "COMPRA ANTICIPADA",
        title: "Asegura tu pedido antes de que se agote",
        bullets: [
          "Disponibilidad garantizada",
          "Salta la fila con tu n\xFAmero de orden"
        ],
        steps: [
          "Elige tu evento y arma tu pedido",
          "Paga por adelantado en segundos",
          "El d\xEDa del show das tu n\xFAmero de orden y retiras"
        ],
        imageAlt: "Persona revisando eventos activos en laptop con Ronda Priv\xE9"
      },
      seat: {
        label: "COMPRA DESDE EL ASIENTO",
        title: "Recibe sin moverte de tu asiento",
        badge: "Exclusivo de Ronda Priv\xE9",
        bullets: [
          "Cero filas, cero interrupciones",
          "Llega directo a tu mano"
        ],
        steps: [
          "Escanea el QR de tu asiento",
          "Compra desde tu celular",
          "Recibe en tu ubicaci\xF3n sin moverte"
        ],
        imageAlt: "Mozo entregando bebida en asiento VIP durante concierto"
      },
      pickup: {
        label: "COMPRA Y RETIRA",
        title: "Tu pedido listo cuando llegas",
        bullets: [
          "Sin esperar, sin filas"
        ],
        steps: [
          "Pide desde tu celular en cualquier momento",
          "La pantalla se pone verde cuando est\xE1 listo",
          "Das tu n\xFAmero de orden y retiras"
        ],
        imageAlt: "Persona retirando su pedido en un bar de festival"
      }
    }
  },
  statsBar: {
    items: [
      { value: "85%", label: "Reducci\xF3n de filas" },
      { value: "+40%", label: "M\xE1s ventas" },
      { value: "3x", label: "Velocidad de servicio" },
      { value: "0", label: "Infraestructura extra" }
    ]
  },
  dashboardPreview: {
    eyebrow: "Panel de control",
    headline: "Todo bajo control.",
    headlineHighlight: "En tiempo real.",
    description: "Un dashboard completo para organizadores y equipos operativos. Visualiza ventas, controla disponibilidad y toma decisiones informadas al instante.",
    modules: [
      { title: "Estad\xEDsticas r\xE1pidas", subtitle: "KPIs en tiempo real" },
      { title: "Gesti\xF3n de productos", subtitle: "Men\xFAs y precios" },
      { title: "Disponibilidad en vivo", subtitle: "Quiebres al instante" },
      { title: "Anal\xEDticas", subtitle: "Insights de consumo" },
      { title: "Monitoreo de ventas", subtitle: "Seguimiento continuo" },
      { title: "Comportamiento", subtitle: "Patrones de consumo" },
      { title: "Control de pedidos", subtitle: "Estado en tiempo real" },
      { title: "Decisiones r\xE1pidas", subtitle: "Datos para actuar" }
    ],
    mock: {
      windowTitle: "Ronda Priv\xE9",
      liveBadge: "En vivo",
      eventName: "Festival Verano Sur 2026 \xB7 Noche 3",
      eventMeta: "Arena Sur \xB7 18 comercios \xB7 9.200 asistentes",
      updatedAgo: "Actualizado hace {{seconds}} seg",
      vsYesterday: "vs ayer",
      units: {
        min: "min",
        sec: "s"
      },
      kpis: {
        gmv: "GMV en curso",
        orders: "Pedidos",
        avgTicket: "Ticket promedio",
        avgWait: "Espera promedio"
      },
      chart: {
        title: "Ventas en tiempo real",
        legend: "Ventas (acumulado)",
        open: "Apertura",
        now: "Ahora"
      },
      bars: {
        title: "Estado de barras",
        items: [
          {
            name: "Barra Interior",
            status: "Operando con normalidad"
          },
          {
            name: "Barra VIP",
            status: "Operando con normalidad"
          },
          {
            name: "Barra Exterior",
            status: "Demanda alta"
          },
          {
            name: "Patio de comidas",
            status: "Demanda muy alta"
          }
        ]
      },
      orders: {
        title: "Pedidos recientes",
        viewAll: "Ver todos los pedidos",
        pool: [
          {
            items: "2 Piscolas",
            status: "Preparando"
          },
          {
            items: "4 Cervezas",
            status: "Listo"
          },
          {
            items: "Combo VIP",
            status: "En preparaci\xF3n"
          },
          {
            items: "3 Aguas minerales",
            status: "Listo"
          },
          {
            items: "2 Hamburguesas",
            status: "Preparando"
          },
          {
            items: "1 Tabla para compartir",
            status: "En preparaci\xF3n"
          }
        ]
      },
      channels: {
        title: "Ventas por canal",
        pickup: "Compra y Retira",
        seat: "Compra desde el Asiento",
        preorder: "Compra Anticipada"
      },
      disclaimer: "Datos demostrativos \xB7 evento ficticio de 9.200 asistentes"
    },
    ctaQuestion: "\xBFQuieres verlo con los datos de tu venue?"
  },
  industriesPreview: {
    eyebrow: "Adaptable a tu recinto",
    title: "Una soluci\xF3n, m\xFAltiples formatos",
    subtitle: "Selecciona tu tipo de recinto y descubre c\xF3mo Ronda Priv\xE9 se adapta a tus necesidades espec\xEDficas",
    labels: {
      problem: "El problema",
      solution: "Nuestra soluci\xF3n",
      useCases: "Ejemplos de uso"
    },
    ctaTalk: "Hablemos sobre {{industry}}",
    useCases: {
      nightclubs: [
        "Pedidos desde mesa VIP",
        "Compra y Retira en barra",
        "Promociones en tiempo real",
        "Control de stock"
      ],
      festivals: [
        "Puntos de Compra y Retira",
        "Compra anticipada masiva",
        "Reducci\xF3n de filas 80%",
        "M\xE1s ventas por persona"
      ],
      stadiums: [
        "Delivery al asiento",
        "QR por sector",
        "Servicio en suites",
        "Compra anticipada"
      ],
      bars: [
        "QR en mesas",
        "Compra y Retira en barra",
        "Control de stock en vivo",
        "M\xE9tricas por hora"
      ]
    }
  },
  consent: {
    ariaLabel: "Aviso de cookies",
    message: "Usamos cookies para entender c\xF3mo se usa el sitio y mejorar la experiencia. Puedes aceptar todas o quedarte solo con las necesarias.",
    acceptOnly: "Solo necesarias",
    accept: "Aceptar"
  }
};

// src/lib/mcp/tools/list-faq.ts
var faqDict = es_default.faq ?? {};
var asString = (v) => typeof v === "string" ? v : "";
var list_faq_default = defineTool3({
  name: "list_faq",
  title: "List FAQ",
  description: "List Ronda Priv\xE9 frequently asked questions with answers (Spanish). Optionally filter by category.",
  inputSchema: {
    category: z3.enum(["general", "attendees", "organizers", "technical"]).optional().describe("Filter by FAQ category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const rows = faqItems.filter((f) => category ? f.category === category : true).map((f) => ({
      id: f.id,
      category: f.category,
      question: asString(faqDict[f.questionKey.replace(/^faq\./, "")]),
      answer: asString(faqDict[f.answerKey.replace(/^faq\./, "")])
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { faq: rows }
    };
  }
});

// src/lib/mcp/tools/list-glossary.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z4 } from "npm:zod@^4.4.3";

// src/data/glossary.ts
var GLOSSARY_TERMS = [
  // Modalidades de venta
  { id: "compra-anticipada", category: "sales" },
  { id: "compra-y-retiro", category: "sales" },
  { id: "entrega-en-asiento", category: "sales" },
  { id: "fila-digital", category: "sales" },
  { id: "numero-de-orden", category: "sales" },
  // Operación de venue
  { id: "punto-de-venta", category: "venue" },
  { id: "totem-de-autoservicio", category: "venue" },
  { id: "carta-digital", category: "venue" },
  { id: "inventario-tiempo-real", category: "venue" },
  { id: "dashboard", category: "venue" },
  // Tecnología
  { id: "pwa", category: "tech" },
  { id: "qr", category: "tech" },
  { id: "modo-cache", category: "tech" },
  { id: "trazabilidad", category: "tech" },
  { id: "cloud", category: "tech" },
  // Tipos de recinto
  { id: "venue", category: "spaces" },
  { id: "suite", category: "spaces" },
  { id: "palco", category: "spaces" },
  { id: "hospitality", category: "spaces" },
  { id: "festival", category: "spaces" },
  { id: "coffee-shop", category: "spaces" },
  // Métricas del negocio
  { id: "ticket-promedio", category: "metrics" },
  { id: "tiempo-de-espera", category: "metrics" },
  { id: "rotacion-de-barra", category: "metrics" },
  { id: "tasa-de-conversion", category: "metrics" }
];

// src/lib/mcp/tools/list-glossary.ts
var terms = es_default.glossary?.terms ?? {};
var list_glossary_default = defineTool4({
  name: "list_glossary",
  title: "List glossary",
  description: "List Ronda Priv\xE9 industry glossary terms with definitions (Spanish). Optionally filter by category or search text.",
  inputSchema: {
    category: z4.enum(["sales", "venue", "tech", "spaces", "metrics"]).optional().describe("Filter by glossary category."),
    search: z4.string().optional().describe("Case-insensitive substring match on term or definition.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, search }) => {
    const q = search?.toLowerCase();
    const rows = GLOSSARY_TERMS.filter((g) => category ? g.category === category : true).map((g) => ({
      id: g.id,
      category: g.category,
      term: terms[g.id]?.term ?? g.id,
      definition: terms[g.id]?.definition ?? ""
    })).filter((r) => q ? r.term.toLowerCase().includes(q) || r.definition.toLowerCase().includes(q) : true);
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { glossary: rows }
    };
  }
});

// src/lib/mcp/tools/list-insights.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z as z5 } from "npm:zod@^4.4.3";

// src/data/insights.ts
var insights = [
  {
    id: "increase-sales-events",
    slug: "aumentar-ventas-fnb-eventos",
    titleKey: "insights.post1.title",
    excerptKey: "insights.post1.excerpt",
    category: "cases",
    date: "2026-03-25",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    readTime: 5
  },
  {
    id: "future-fnb-tech",
    slug: "futuro-tecnologia-fnb-eventos",
    titleKey: "insights.post2.title",
    excerptKey: "insights.post2.excerpt",
    category: "trends",
    date: "2026-03-20",
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
    readTime: 7
  },
  {
    id: "reduce-queues-stadiums",
    slug: "reducir-filas-estadios",
    titleKey: "insights.post3.title",
    excerptKey: "insights.post3.excerpt",
    category: "cases",
    date: "2026-03-15",
    image: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&q=80",
    readTime: 4
  },
  {
    id: "inventory-management",
    slug: "inventario-tiempo-real-eventos",
    titleKey: "insights.post4.title",
    excerptKey: "insights.post4.excerpt",
    category: "product",
    date: "2026-03-10",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80",
    readTime: 6
  },
  {
    id: "nightclub-innovation",
    slug: "innovacion-nightclubs-venta-digital",
    titleKey: "insights.post5.title",
    excerptKey: "insights.post5.excerpt",
    category: "industry",
    date: "2026-03-05",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80",
    readTime: 5
  },
  {
    id: "pre-purchase-strategy",
    slug: "compra-anticipada-maximiza-ingresos",
    titleKey: "insights.post6.title",
    excerptKey: "insights.post6.excerpt",
    category: "product",
    date: "2026-02-28",
    image: "https://images.unsplash.com/photo-1551818255-e6e10975bc17?w=800&q=80",
    readTime: 4
  }
];

// src/lib/mcp/tools/list-insights.ts
var dict = es_default.insights ?? {};
var list_insights_default = defineTool5({
  name: "list_insights",
  title: "List insights",
  description: "List Ronda Priv\xE9 insight articles (blog posts) with title and excerpt (Spanish). Optionally filter by category.",
  inputSchema: {
    category: z5.enum(["trends", "cases", "product", "industry"]).optional().describe("Filter by insight category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const rows = insights.filter((p) => category ? p.category === category : true).map((p) => {
      const key = p.titleKey.replace(/^insights\./, "").replace(/\.title$/, "");
      const entry = dict[key] ?? {};
      return {
        id: p.id,
        slug: p.slug,
        category: p.category,
        date: p.date,
        readTime: p.readTime,
        title: entry.title ?? "",
        excerpt: entry.excerpt ?? "",
        url: `https://rondaprive.com/es/insights/${p.slug}`
      };
    });
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { insights: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ronda-prive-mcp",
  title: "Ronda Priv\xE9",
  version: "0.1.0",
  instructions: "Public tools for Ronda Priv\xE9 (rondaprive.com), an event-monetization platform for arenas, festivals and venues. Use these tools to browse showcase events, look up FAQ answers, glossary terms and insight articles.",
  tools: [list_events_default, get_event_default, list_faq_default, list_glossary_default, list_insights_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
